### PR TITLE
#654: Fix user ZIP code validation regex

### LINKED ISSUE #654: User ZIP validation allows invalid ZIP codes
Presently the validation for a user's ZIP code is:
```
 validates_format_of :postal_code, 
                    with: /\A\d{5}-\d{4}|\A\d{5}\z/, 
                    message: "should be 12345 or 12345-1234", 
                    allow_blank: true 
```
As I understand it ZIP codes can either be 5 digits or 9 digit ZIP+4. The regex is missing the terminating character (`\z`) in the first alternative, which means the regex that is intended to match 4 digits matches anything starting with 4 digits. It looks like it's intended to be:
`/\A\d{5}-\d{4}\z|\A\d{5}\z/`

An example of an inappropriate match can be illustrated with, e.g.:
`User.new(name: "a", email: "a@b.c", country: "USA", region: "ON", postal_code: "12345-1234-Not-a-valid-postal-code...").save!`

Perhaps it'd be slightly more clear to use an optional instead of alternate, e.g. `\A\d{5}(?:-\d{4})?\z`?

ZIP codes that have slipped through the cracks can likely be found with a query, e.g.:
`SELECT id, name, email, postal_code FROM users WHERE postal_code !~ '\A\Z|\A\d{5}(?:-\d{4})?\Z';`

### PR DESCRIPTION
**Pull request by tobymurray**
Before this fix is merged, the production database should be checked for invalid data. For example, anything returned by:
`SELECT id, name, email, postal_code FROM users WHERE postal_code !~ '\A\Z|\A\d{5}(?:-\d{4})?\Z';`
will be invalid after this has been merged.

Fixes #654. The regular expression used was missing the terminating character in the first alternative expression. This means that any value could be used for the ZIP so long as it started with 5 digits followed by 4 digits.

### CODE REVIEW

File: spec/models/user_spec.rb [hunk 1]
```diff
@@ -156,6 +156,11 @@
         user.valid?
         expect(user.errors[:postal_code]).to include('should be 12345 or 12345-1234')
       end
+      it 'is invalid with a zip code that starts valid but contains more digits' do
+        user = build(:user, postal_code: '12345-12345')
+        user.valid?
```
Comment (TheDudeWithTheThing) [inline spec/models/user_spec.rb]: `expect(user).not_to be_valid`

Comment (TheDudeWithTheThing) [reply spec/models/user_spec.rb]: probably change the other 2 above as well

Comment (tobymurray) [reply spec/models/user_spec.rb]: Can do - did so in dae7f03

**Comment by markottaviani** [comment]
Prod Database verified and cleaned up!
